#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : requests
Version  : 2.23.0
Release  : 81
URL      : https://files.pythonhosted.org/packages/f5/4f/280162d4bd4d8aad241a21aecff7a6e46891b905a4341e7ab549ebaf7915/requests-2.23.0.tar.gz
Source0  : https://files.pythonhosted.org/packages/f5/4f/280162d4bd4d8aad241a21aecff7a6e46891b905a4341e7ab549ebaf7915/requests-2.23.0.tar.gz
Summary  : Python HTTP for Humans.
Group    : Development/Tools
License  : Apache-2.0
Requires: requests-license = %{version}-%{release}
Requires: requests-python = %{version}-%{release}
Requires: requests-python3 = %{version}-%{release}
Requires: PySocks
Requires: certifi
Requires: chardet
Requires: idna
Requires: urllib3
BuildRequires : PySocks
BuildRequires : buildreq-distutils3
BuildRequires : certifi
BuildRequires : chardet
BuildRequires : idna
BuildRequires : urllib3

%description
<span align="center">
        
        <pre>

%package license
Summary: license components for the requests package.
Group: Default

%description license
license components for the requests package.


%package python
Summary: python components for the requests package.
Group: Default
Requires: requests-python3 = %{version}-%{release}

%description python
python components for the requests package.


%package python3
Summary: python3 components for the requests package.
Group: Default
Requires: python3-core

%description python3
python3 components for the requests package.


%prep
%setup -q -n requests-2.23.0
cd %{_builddir}/requests-2.23.0

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1582148267
export GCC_IGNORE_WERROR=1
export CFLAGS="$CFLAGS -fno-lto "
export FCFLAGS="$CFLAGS -fno-lto "
export FFLAGS="$CFLAGS -fno-lto "
export CXXFLAGS="$CXXFLAGS -fno-lto "
export MAKEFLAGS=%{?_smp_mflags}
python3 setup.py build

%check
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
python test_requests.py || :
%install
export MAKEFLAGS=%{?_smp_mflags}
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/requests
cp %{_builddir}/requests-2.23.0/LICENSE %{buildroot}/usr/share/package-licenses/requests/e6b8036f895736f9779f09d06d28265ea5f74f1d
python3 -tt setup.py build  install --root=%{buildroot}
echo ----[ mark ]----
cat %{buildroot}/usr/lib/python3*/site-packages/*/requires.txt || :
echo ----[ mark ]----

%files
%defattr(-,root,root,-)

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/requests/e6b8036f895736f9779f09d06d28265ea5f74f1d

%files python
%defattr(-,root,root,-)

%files python3
%defattr(-,root,root,-)
/usr/lib/python3*/*
